### ISSUE TITLE
Presmerovat neprihlasenych userov na verejne vysledky z neexistujucich url, alebo aspon z /, alebo mozno zo vsetkych neverejnych url?

### ISSUE THREAD

**Issue by michalmasrna1** [ZdruzenieSTROM/sutazeStrom#18]
Bude to potom menej prijemne pre adminov, lebo musia na login ist priamo podla url, na druhu stranu nemusia ucitelia prepisovat dlhsie url a nemozu omylom stupit niekam zle a dostat sa na admina. Aj ked aj tak to asi pojde iba cez qr, lebo by museli rucne opisovat ipcku.

**Comment by kovacspe** [comment]
@michalmasrna1  toto by sme si mohli specifikovať ako chceme. Mne možno príde rozumné:
- 404 handler na priebezne vysledky aktualne beziacej sutaze (Spoliha na to ze bezi iba jedna)
- / Ak si neprihlaseny mozno ti vratit nejaky raycestnik na prihlasenie alebo vysledky ?
- Ak si neprihlaseny a ides na existujucu url ... asi ta presmerovat na login

**Comment by michalmasrna1** [comment]
No neviem mne pride zvlastne posielat verejnost na login alebo im vobec ukazovat ze taka moznost existuje, zbytocne to moze viest k zmatku. Ja osobne by som vsetkych neprihlasenych odvsadial presmeroval na aktualne vysledky okrem /admin kde by som nechal to aktualne presmerovanie na admin login odkial sa budu prihlasovat organizatori.
