### ISSUE TITLE
Pridať endpoint pre aktuálne priebežné výsledky

### ISSUE THREAD

**Issue by kovacspe** [ZdruzenieSTROM/sutazeStrom#22]

**Comment by kovacspe** [comment]
@michalmasrna1. Toto má byť náhľad pre stuff? Možno by sme mohli /vysledky renderovať vždy ako nezmrazené? a priebezne mraziť?

**Comment by michalmasrna1** [comment]
Nie som si isty co tym bolo myslene povodne ale podla mna ano podla mna chceme aby /results zobrazovalo nezmrazene vysledky cely cas a nejak to vizualne odlisit (to mozem aj ja potom spravit) nech si ludia nepomylia tie verejne a sukromne a nahodou nezacnu premietat tie sukromne vysledky.

**Comment by kovacspe** [comment]
No pozeral som na kód a mám za to že to je teraz presne tak ako to chceme. Viš to prosím odskúšať? Tie zmrazené sa zobrazuju iba pri nahlade tych public.

**Comment by michalmasrna1** [comment]
Hej je to tak. Tak potom asi nic z tejto issue.
